---
- name: Install xdebug.
  become: true
  apt: package=php-xdebug state=latest

- name: Unlink xdebug configuration (fpm, cli)
  become: true
  file: >
    dest={{ item }}
    state=absent
  with_items:
    - /etc/php/7.0/fpm/conf.d/20-xdebug.ini
    - /etc/php/7.0/cli/conf.d/20-xdebug.ini

- name: Configure xdebug for fpm
  become: true
  template: >
    src=xdebug.fpm.ini
    dest=/etc/php/7.0/fpm/conf.d/20-xdebug.ini
    owner="root" group="root" mode=0644
  notify:
    - restart php7-fpm

- name: Display php errors
  ini_file: dest=/etc/php/7.0/fpm/php.ini
            section=PHP
            option=display_errors
            value=On
            backup=yes
  notify:
    - restart php7-fpm

- name: Error Reporting
  ini_file: dest=/etc/php/7.0/fpm/php.ini
            section=PHP
            option=display_errors
            value=E_ALL
            backup=yes
  notify:
    - restart php7-fpm
