---
- name: ensure timezone is set in fpm php.ini
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=date
            option=date.timezone
            value="{{php_timezone}}"
            backup=yes
  notify:
    - restart php7-fpm

- name: Enable opcache
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=opcache
            option=opcache.enable
            value=1
            backup=yes
  notify:
    - restart php7-fpm

- name: Display errors
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=PHP
            option=display_errors
            value=On
            backup=yes
  notify:
    - restart php7-fpm

- name: Startup errors
  ini_file: dest=/etc/php/7.0/cli/php.ini
            section=PHP
            option=display_startup_errors
            value=On
            backup=yes
  notify:
    - restart php7-fpm
